// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfCV3vUNYbONxummMRQ6Z8SsOPUAPErGU',
    appId: '1:504992601174:web:8477753d4672b4c43c17f7',
    messagingSenderId: '504992601174',
    projectId: 'fb-cursos-intersemestrales',
    authDomain: 'fb-cursos-intersemestrales.firebaseapp.com',
    storageBucket: 'fb-cursos-intersemestrales.firebasestorage.app',
    measurementId: 'G-5FFDEC1X66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsB5wXhObVNEv5a5xiVsQUs6KH3F7qNy8',
    appId: '1:504992601174:android:56507d00700d75443c17f7',
    messagingSenderId: '504992601174',
    projectId: 'fb-cursos-intersemestrales',
    storageBucket: 'fb-cursos-intersemestrales.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFyRmt_Q_LrKQYgYY0zYEKxpxkcXr0Cf4',
    appId: '1:504992601174:ios:0d1c8dc6b4df72cf3c17f7',
    messagingSenderId: '504992601174',
    projectId: 'fb-cursos-intersemestrales',
    storageBucket: 'fb-cursos-intersemestrales.firebasestorage.app',
    iosBundleId: 'com.example.cwtEcommerceAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFyRmt_Q_LrKQYgYY0zYEKxpxkcXr0Cf4',
    appId: '1:504992601174:ios:0d1c8dc6b4df72cf3c17f7',
    messagingSenderId: '504992601174',
    projectId: 'fb-cursos-intersemestrales',
    storageBucket: 'fb-cursos-intersemestrales.firebasestorage.app',
    iosBundleId: 'com.example.cwtEcommerceAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfCV3vUNYbONxummMRQ6Z8SsOPUAPErGU',
    appId: '1:504992601174:web:98d79a8e174928373c17f7',
    messagingSenderId: '504992601174',
    projectId: 'fb-cursos-intersemestrales',
    authDomain: 'fb-cursos-intersemestrales.firebaseapp.com',
    storageBucket: 'fb-cursos-intersemestrales.firebasestorage.app',
    measurementId: 'G-FC1HQT36EB',
  );

}